name: Build and Release Jar

on:
  push:
    tags:
      - '*.*.*'  # 当推送符合此模式的标签时触发
  workflow_dispatch:
    inputs:
      tag_name:
        description: "发布辛巴本"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 设置 JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: 授予 gradlew 执行权限
        run: chmod +x ./gradlew

      - name: 使用 Gradle 构建
        run: ./gradlew shadowJar

      - name: 上传构建产物
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: build/libs/iCrypto-*-SNAPSHOT-all.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: package
          path: build/libs

      - name: 创建发布
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
          name: ${{ github.event.inputs.tag_name || github.ref_name }}
          files: build/libs/iCrypto-*-SNAPSHOT-all.jar
          token: ${{ secrets.GITHUB_TOKEN }}
