name: Build and Release Jar

on:
  push:
    tags:
      - 'v*.*.*'  # 当推送符合此模式的标签时触发

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 设置 JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: 授予 gradlew 执行权限
        run: chmod +x ./gradlew

      - name: 使用 Gradle 构建 JAR
        run: ./gradlew shadowJar

      - name: 上传构建产物到工作流
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: build/libs/iCrypto-*-SNAPSHOT-all.jar

      - name: 下载构建产物
        uses: actions/download-artifact@v2
        with:
          name: package
          path: build/libs

      - name: 创建并发布 GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: build/libs/iCrypto-*-SNAPSHOT-all.jar
          token: ${{ secrets.GITHUB_TOKEN }}